"""init

Revision ID: 6f128a0f6a7a
Revises:
Create Date: 2025-12-26 04:49:57.308052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f128a0f6a7a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_station",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_daily_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("temp_min_c", sa.Float(), nullable=False),
        sa.Column("temp_max_c", sa.Float(), nullable=False),
        sa.Column("temp_avg_c", sa.Float(), nullable=False),
        sa.Column("precipitation_mm_total", sa.Float(), nullable=False),
        sa.Column("wind_speed_avg_ms", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"], ["weather_station.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weather_daily_summary_station_date",
        "weather_daily_summary",
        ["station_id", "date"],
        unique=True,
    )
    op.create_table(
        "weather_measurement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=False),
        sa.Column("humidity_pct", sa.Float(), nullable=False),
        sa.Column("pressure_hpa", sa.Float(), nullable=False),
        sa.Column("wind_speed_ms", sa.Float(), nullable=False),
        sa.Column("wind_dir_deg", sa.Integer(), nullable=False),
        sa.Column("precipitation_mm", sa.Float(), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"], ["weather_station.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weather_measurement_station_time",
        "weather_measurement",
        ["station_id", "measured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_weather_measurement_station_time", table_name="weather_measurement"
    )
    op.drop_table("weather_measurement")
    op.drop_index(
        "ix_weather_daily_summary_station_date",
        table_name="weather_daily_summary",
    )
    op.drop_table("weather_daily_summary")
    op.drop_table("weather_station")
    # ### end Alembic commands ###
