name: da

services:
    db:
      image: postgres:16
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./db_init:/docker-entrypoint-initdb.d
        - ./dumps:/dumps
        - ./redash_dumps:/redash_dumps
        - ./db_data:/var/lib/postgresql/data

    redis:
      image: redis:7
      restart: always

    server:
      image: redash/redash:latest
      command: server
      depends_on:
        - db
        - redis
      environment:
        REDASH_DATABASE_URL: postgresql://redash:redash@db:5432/redash
        REDASH_REDIS_URL: redis://redis:6379/0
        REDASH_SECRET_KEY: secret-key
        REDASH_WEB_WORKERS: 4
      ports:
        - "8052:5000"
      restart: always

    worker:
      image: redash/redash:latest
      command: worker
      depends_on:
        - server
      environment:
        REDASH_DATABASE_URL: postgresql://redash:redash@db:5432/redash
        REDASH_REDIS_URL: redis://redis:6379/0
        REDASH_SECRET_KEY: secret-key
      restart: always
    
    api:
      links:
        - db
      image: api
      restart: no
      environment:
        DB_NAME: postgres
        DB_PORT: 5432
        DB_PASS: postgres
        DB_USER: postgres
        DB_HOST: db
      build: ./generator
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "10"
      command: python main.py

volumes:
    data:
        driver: local